// <auto-generated />
namespace ClientRegistration.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Wavemigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wavemigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201809061216149_Wave migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
